// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwKU9X0kxJJSm2DUfM6O4Pl4ye0jxhKqk',
    appId: '1:845675734376:web:80db6734850a5e205ca2dd',
    messagingSenderId: '845675734376',
    projectId: 'vehicle-monitoring-app-33d9e',
    authDomain: 'vehicle-monitoring-app-33d9e.firebaseapp.com',
    storageBucket: 'vehicle-monitoring-app-33d9e.firebasestorage.app',
    measurementId: 'G-M4D4LKCXJP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPlICvmTiJkPmtYJFu22lzLSWVS8vgyGk',
    appId: '1:845675734376:android:039bd3eae00aa6fb5ca2dd',
    messagingSenderId: '845675734376',
    projectId: 'vehicle-monitoring-app-33d9e',
    storageBucket: 'vehicle-monitoring-app-33d9e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDDOMD1VEmmGVnfq3s0QrfIcmxU5XdYU2U',
    appId: '1:845675734376:ios:9fba8ba8564c228d5ca2dd',
    messagingSenderId: '845675734376',
    projectId: 'vehicle-monitoring-app-33d9e',
    storageBucket: 'vehicle-monitoring-app-33d9e.firebasestorage.app',
    iosBundleId: 'com.example.vehicleMonitoring',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDDOMD1VEmmGVnfq3s0QrfIcmxU5XdYU2U',
    appId: '1:845675734376:ios:9fba8ba8564c228d5ca2dd',
    messagingSenderId: '845675734376',
    projectId: 'vehicle-monitoring-app-33d9e',
    storageBucket: 'vehicle-monitoring-app-33d9e.firebasestorage.app',
    iosBundleId: 'com.example.vehicleMonitoring',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCwKU9X0kxJJSm2DUfM6O4Pl4ye0jxhKqk',
    appId: '1:845675734376:web:d7db5ec5f44d2e465ca2dd',
    messagingSenderId: '845675734376',
    projectId: 'vehicle-monitoring-app-33d9e',
    authDomain: 'vehicle-monitoring-app-33d9e.firebaseapp.com',
    storageBucket: 'vehicle-monitoring-app-33d9e.firebasestorage.app',
    measurementId: 'G-5YGG3VBR1T',
  );
}
